version: "3"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - PORT = :8081
      - JWT_SECRET = your_secret_access_token_jwt
      - EXPIRES_IN = 24
      - DB_HOST=db
      - DB_PASSWORD=secret
      - DB_NAME=myapp
      - DB_PORT=3306
    ports:
      - 8081:8081
    volumes:
      - .:/app
    depends_on:
      - db
  db:
    image: mysql:latest
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=myapp
    volumes:
      - db-data:/var/lib/mysql
volumes:
  db-data:
