name: Go

on:
  push:
    branches:
      - main
      - deploy/docker
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19

      - name: Set up Docker
        uses: docker/setup-buildx-action@v1

      - name: Test Actor
        run: go test -v ./modules/actor

      - name: Test Customer
        run: go test -v ./modules/customer

      - name: Install Docker Compose
        uses: isbang/compose-action@v1.4.1
        with:
          compose-file: "./docker-compose.yaml"

      - name: build docker-compose
        run: docker-compose build

      - name: Run docker-compose
        run: docker-compose up -d
